name: Build EXE

on:
  push:
    paths:
      - '**.cpp'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Compile C++ file
      run: |
        g++ -o programme.exe *.cpp

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: programme
        path: programme.exe
