name: Build Windows EXE

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: Compile with g++
      run: |
        g++ Minecraft.cpp ressource.o -o Minecraft.exe -lgdi32 -luser32 -lshell32 -lcomctl32 -lwinmm -lole32

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-exe
        path: Minecraft.exe
