name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW via Chocolatey
      run: choco install mingw -y

    - name: Add MinGW to PATH
      run: echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" >> $env:GITHUB_PATH

    - name: Compile with g++
      run: |
        g++ Minecraft.cpp ressource.o -o Minecraft.exe -lgdi32 -luser32 -lshell32 -lcomctl32 -lwinmm -lole32

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: Minecraft-exe
        path: Minecraft.exe
